version: '3.8'
services:
  app:
    image: catan-app
    working_dir: /app
    build: 
      context: ./go
      dockerfile: Dockerfile
    container_name: catanapp
    environment:
      - GO_ENV=development
    ports:
      - "3000:3000"
    volumes:
    - ./go:/app
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - app

